# IRIS Context Policy
policies:
  high:
    execution_mode: "parallel"
    turns: 100
    cycles: 25
    mirrors: "all"
    max_pressure: 2
  medium:
    execution_mode: "parallel"
    turns: 50
    cycles: 12
    mirrors: "high_capacity"
    max_pressure: 2
  low:
    execution_mode: "parallel"
    turns: 20
    cycles: 5
    mirrors: "local_only"
    max_pressure: 3
