# IRIS Model Configuration
mirrors:
  high_capacity:
    - id: "anthropic_claude-sonnet-4.5"
      params: "~500B"
      confidence_baseline: 0.80
    - id: "openai_gpt-4o"
      params: "~671B"
      confidence_baseline: 0.75
    - id: "xai_grok-4-fast-reasoning"
      params: "~314B"
      confidence_baseline: 0.75
    - id: "google_gemini-2.5-flash-lite"
      params: "~200B"
      confidence_baseline: 0.70
    - id: "deepseek_deepseek-chat"
      params: "~236B"
      confidence_baseline: 0.70
  local:
    - id: "ollama_qwen3_1.7b"
      params: "1.7B"
      confidence_baseline: 0.60
    - id: "ollama_llama3.2_3b"
      params: "3B"
      confidence_baseline: 0.65
