# IRIS Run Limits
pressure:
  max_allowed: 2
  warning_threshold: 2
  critical_threshold: 3
consensus:
  min_agreement_for_wet_lab: 0.90
  max_outlier_fraction: 0.15
s4_convergence:
  min_ratio: 0.90
  min_cycles_for_stability: 10
monte_carlo:
  recommended_runs: 300
  recommended_mirrors: 7
